import { Article } from "./article";

export const ARTICLES: Article[] = [
    new Article(2, "Wish me luck on the Databricks Data Analyst Associate Exam", "This is test, may have many characters, sper ca over the limit. tu ce zici? O zi buna iti doresc. Pa", "23.01.2025", ["it", "devexp"]),
    new Article(1, 
        "Snowflake! How did I earn the SnowPro Core Certification with no prior knowledge", 
        "<p>Hooray. Congratulate me 😀. With a busy schedule, a full life and some constant pressure to perform better, I have achieved a new success towards the end of 2024. I earned the certification called SnowPro Core, by Snowflake. How did I do it? How did my learning journey look? And how did I manage to succeed at an exam for a technology I haven't heard about before? I will answer to all of this below.</p>" +
        "<p>First of all, I have to admit. Discipline helped  me a lot. I would love to tell you how in fact it was truly easy, but my truth is that this required methodic, constant, and consequent study. Learning an unfamiliar technology is not something to do on a whim.</p>" +
        "<p>Then, some strategic planning helped me get to my goal. I first spent some time to get a glimpse of all posible materials to study from. Then, after some filtering and sorting through them, I set up a list of materials I would want to go through, and scheduled dedicated time for studying, daily. The format of the content studied was varied - from articles, to video courses, to practice quizzes. I made sure this variation removes a bit of the \"boredom\" that might appear in such cases.</p>"+
        "<p>Then, after consuming a considerable amount of information, I moved to trying practice tests and checking how I score. I decided to do this once I was confident about ~60-70% that I could pass the exam. I believe this is a good time to start testing yourself, and seeing how are you doing. There are lots of practice tests online for most technical exams, some free, some paid. But I think it's important to first spend a good time in accumulating knowledge before you test yourself. If you start with the tests and having zero knowledge, I believe this would lead to low scores on your first tests, which might be discouraging or demotivating. </p>"+
        "<p>Sometimes, technical concepts might be difficult to grasp without actual practice, playing around with code, trying to understand how it acts and why. There is a clear difference between learning in a theoretical mode and learning in a practical mode when it comes to coding. Each of us has their own preferred ways to learn. But each exam also has its own particularities and structure, and I believe that this is also a major factor that people should take into account when signing up for it. In my personal experience with this specific Snowflake exam, I did not consider necessary to incorporate very practical, hands-on, lab-style learning. I thought the theoretical concepts and few code examples given by trainers are enough. And, as it turns out, my passed exam is (I hope) a good enough proof that at least for my particular case, it worked.</p>"+
        "<p>A little context though, that might have an impact in the final result: I have long term experience with software development, along many technologies. I have never heard of Snowflake before the company I work at strongly encouraged us to get certified. But around the same area,  I would say my SQL knowledge is somewhat above average (7-8 out of 10), and I have basic knowledge about all of the major cloud providers, with some more extensive experience in AWS.</p>" +
        "<p>To wrap up, let's discuss some digits. I love digits. Don't you?</p>" + 
        "<p>I managed to do all of this with clean, consistent planning and commitment, also helped by monitoring and documenting the whole process. The documenting was a premiere for me, and I want to share it because I could finally accurately measure something useful, ready to be shared with others and potentially help them.</p>" + 
        "<p>My plan set to spend at least <strong>1 hour per day learning</strong>. My total preparation time was <strong>54 hours</strong> of learing and training, added up in around <strong>3 weeks</strong>. During this process, I constantly refined the resources I used - sometimes added more materials to study, sometimes removed other materials from the list, but most often I added more. At the end, my plan was to consume content in the size of <strong>57 hours</strong>. But as I mentioned before, some material ended up ignored, and out of this, few hours were not actually done and I considered the 54 mentioned before as enough.</p>" +
        "<p>So lucky for me, it was enough. I am happy and proud to carry this Snowflake badge, as a developer with a better background into data. Since data is a subject that I think will become stronger and stronger with time, I really think this could be of help in future projects or interests. I suggest you look up Snowflake as a tech, and see if it fits any of your needs. And if you ever decide to take one of their exams, I hope this gave you a bit of insight into how it works.</p>", 
        "23 Jan 2025",
        ["it", "devexp", "education"]),
];